### ISSUE TITLE
LevelDB support TODO list

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#254]
### Compile + use the extension
- [x] Windows
- [x] Linux
- [x] Mac

### World I/O
- [x] Support 0.16 and 1.0 worlds read/write
- [x] Support creating new LevelDB worlds (many issues, see below)
- [ ] Add support for limited worlds and null generator to prevent generating missing chunks and messing up the world if re-imported to MCPE
- [x] Support continuing custom flat world layers in MCPE for seamless generation (now as good as it can get I think)
- [x] Clean up legacy and/or not needed entries on save?

### Bugs
- [x] Fix W10 client crashes when re-importing worlds (level.dat issues)
- [x] Fix chunk lighting issues when world opened by client
- [x] Fix lighting bugs when a chunk is saved before being light-populated (obsolete since MCPE doesn't save light to disk anymore)

#### Dependency issues
- [x] Segmentation fault when creating a LevelDBIterator
- [x] Segmentation fault when include()ing a file after closing a DB

**Comment by dktapps** [comment]
Lighting issues partly fixed, need to work on issues with chunks being saved before light-populated.

**Comment by mhsjlw** [comment]
leveldb-mcpe doesn't build on Android/Mac/Linux we will have to maintain our own fork to fix those builds. My fork from a while ago fixes the build on these platforms, just cherry pick some of the changes I made and you should be good to go, I'll give it a try when I get a chance

**Comment by llronaldoll** [comment]
How to use world levelDB in pm-pm

**Comment by dktapps** [comment]
You need to compile PHP with the [php-leveldb bindings](https://github.com/reeze/php-leveldb/tree/php7) along with [Mojang's leveldb](https://github.com/Mojang/leveldb-mcpe). More details will be released once we get support for noted platforms.

**Comment by ICrashHD** [comment]
www.pornhub.com/pornstar/leah-gotti

**Comment by TheDiamondYT1** [comment]
Is the light buge fixed now due to ekylight being implemented?
