### ISSUE TITLE
Chunk sending improvements

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#262]
### Issue description
- Chunks are sent in a square spiral. They should be sent in a circle, or diamond. At full render this will cause about 20% more chunks to be sent than needed, due to the fact that you can't see the corners anyway.
- The radius calculation is off. Default `max-chunks` around a player is 192. This is actually just under 7 chunks render-distance. Considering a lot of devices these days have them cranked up to 14, and some like W10 can go right up to 56, this is a little off. It results in clearly-visible edges to the world, while the terrain should fade into the horizon. For 14 render-distance the server should actually be sending ~615 chunks in a _circle_ around the player.
- RequestChunkRadius/ChunkRadiusUpdated are not used correctly: `max-chunks` is totally ignored when a player changes their render distance. A W10 player for example, changing radius to 56, could cause the server to load nearly 13,000 chunks and cause a crash.

**Comment by dktapps** [comment]
View distance is also completely wrong: in PocketMine it's actually treated as the total number of chunks. It should be the chunk radius.

**Comment by xxFlare** [comment]
@dktapps 

Also some problems with orderChunks():
- Chunks are ordered on schedule rather then logic (Every 200 ticks, or 20 ticks when a player moves. A better way to do it is when a player moves a significant distance)
- Chunks order twice when you join due to the teleport function being called and chunkOrderRun set to 5 by default.

**Comment by dktapps** [comment]
I actually observe chunk ordering is called 3 times on join 🤔

**Comment by dktapps** [comment]
### TODO
- [ ] Send chunks in circles as it is done in vanilla MCPE
- [ ] Fix an issue where the edges of the world becomes visible when a player moves, but not into another chunk.
- [ ] Order chunks ondemand instead of on schedule

**Comment by xxFlare** [comment]
@dktapps Interesting... chunks used to actually send in circles. https://github.com/pmmp/PocketMine-MP/commit/f133154919e8fe340972e4beb12b2ba7b6d478fe

> Fix an issue where the edges of the world becomes visible when a player moves, but not into another chunk. (client-sided rendering issue with adjacent unloaded chunks)

Is this the bug where you load a chunk, moving away until its unloaded, and when you come back it just won't load client side?

**Comment by dktapps** [comment]
no. It's a client-sided rendering issue where chunks are invisible if there's an unloaded chunk next to it. See MiNET wiki.

How it used to be done two years ago is not relevant. What matters is how it works _now_.

**Comment by dktapps** [comment]
77b9feb3c01c3d504a19a609aa9647e7f741f18b addresses scheduled chunk sending. The invisible chunks bug is not worth the hassle to fix.
